apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cinemaabyss-ingress
  namespace: cinemaabyss
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: cinemaabyss.example.com
      http:
        paths:
          # Общий префикс для events API
          - path: /api/events
            pathType: Prefix
            backend:
              service:
                name: events-service
                port:
                  number: 8082
          # Все остальное через proxy
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-service
                port:
                  number: 8000